name: Run Go Module
on: [workflow_dispatch]
jobs:
  run-example:
    name: Run Example
    # Because newer is always better, right?
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repository
        uses: actions/checkout@v2
      - id: try-and-build
        run: |
          wget https://golang.org/dl/go1.15.8.linux-amd64.tar.gz
          tar -C ./ -xzf go1.15.8.linux-amd64.tar.gz
          export PATH=$PATH:./go/bin
          go version
          go build ./module-one/moduleone.go
          go build -o /home/runner/work/go-module-example/go-module-example/moduletwo ./module-two/moduletwo.go
          ./moduletwo
          