name: Run Go Module
on: [workflow_dispatch]
jobs:
  run-example:
    name: Run Example
    # Because newer is always better, right?
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: post-checkout
        run: |
          ls /
