name: Run Go Module
on: [workflow_dispatch]
jobs:
  run-example:
    name: Run Example
    # Because newer is always better, right?
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repository
        uses: actions/checkout@v2
      - id: try-and-build
        run: |
          go version
          ls -alt /home/runner/work/go-module-example/go-module-example/
          go build /home/runner/work/go-module-example/go-module-example/module-one/moduleone.go
          cd /home/runner/work/go-module-example/go-module-example/module-two
          go build -o moduletwo ./moduletwo.go
          ./moduletwo
          